#!/bin/bash
export SCHRODINGER=/home/emilio/schrodinger/r2012/b1
export IMP_ROOT=$SCHRODINGER/impact-v5.8
export IMPACT_EXEC=$SCHRODINGER/impact-v5.8/bin/Linux-x86_64
export MMSHARE_EXEC=$SCHRODINGER/mmshare-v2.1/bin/Linux-x86_64
export LD_LIBRARY_PATH=$SCHRODINGER/mmshare-v2.1/lib/Linux-x86_64:$LD_LIBRARY_PATH
export OMP_NUM_THREADS=1
$IMPACT_EXEC/main1m.e2 $1
